# coding: utf-8

"""
    KS Trade API's

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.ltp_quote import LTPQuote  # noqa: E501
from openapi_client.rest import ApiException

class TestLTPQuote(unittest.TestCase):
    """LTPQuote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LTPQuote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.ltp_quote.LTPQuote()  # noqa: E501
        if include_optional :
            return LTPQuote(
                instrumentName = '0', 
                instrumentToken = 56, 
                lastPrice = 1.337
            )
        else :
            return LTPQuote(
        )

    def testLTPQuote(self):
        """Test LTPQuote"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
