# coding: utf-8

"""
    Session-Order-Margin-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.res_new_sor_order import ResNewSOROrder  # noqa: E501
from openapi_client.rest import ApiException

class TestResNewSOROrder(unittest.TestCase):
    """ResNewSOROrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ResNewSOROrder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.res_new_sor_order.ResNewSOROrder()  # noqa: E501
        if include_optional :
            return ResNewSOROrder(
                bse = openapi_client.models.sor_response.SOR Response(
                    price = 1.337, 
                    quantity = 1.337, 
                    mesage = '0', 
                    order_id = '0', ), 
                nse = openapi_client.models.sor_response.SOR Response(
                    price = 1.337, 
                    quantity = 1.337, 
                    mesage = '0', 
                    order_id = '0', )
            )
        else :
            return ResNewSOROrder(
        )

    def testResNewSOROrder(self):
        """Test ResNewSOROrder"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
