# coding: utf-8

"""
    KS Trade API's

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response200_depth import InlineResponse200Depth  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse200Depth(unittest.TestCase):
    """InlineResponse200Depth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse200Depth
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response200_depth.InlineResponse200Depth()  # noqa: E501
        if include_optional :
            return InlineResponse200Depth(
                buy = openapi_client.models.inline_response_200_depth_buy.inline_response_200_depth_buy(
                    price = 1.337, 
                    quantity = 56, 
                    orders = 56, ), 
                sell = openapi_client.models.inline_response_200_depth_buy.inline_response_200_depth_buy(
                    price = 1.337, 
                    quantity = 56, 
                    orders = 56, )
            )
        else :
            return InlineResponse200Depth(
        )

    def testInlineResponse200Depth(self):
        """Test InlineResponse200Depth"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
